---
title: "Instagram learning analysis"
output: html_notebook
---

Let's install packages
```{r}
install.packages("ggthemes")
install.packages("RColorBrewer")
install.packages("rstudioapi")
install.packages("ggdist")
install.packages("MASS")
install.packages("ggeffects")
install.packages("viridis")
devtools::install_github("thomasp85/patchwork")
install.packages("sjPlot")
install.packages("cowplot")
install.packages("effects")
install.packages("robustlmm")

devtools::install_github("mvuorre/brmstools")
```

Let's load those packages
```{r message=FALSE}
library(tidyverse)
library(MASS)
library(ggeffects)
library(effects)
if(!require(psych)){install.packages("psych")}
if(!require(FSA)){install.packages("FSA")}
if(!require(lattice)){install.packages("lattice")}
if(!require(ordinal)){install.packages("ordinal")}
if(!require(car)){install.packages("car")}
if(!require(RVAideMemoire)){install.packages("RVAideMemoire")}
if(!require(multcomp)){install.packages("multcomp")}
if(!require(emmeans)){install.packages("emmeans")}
if(!require(viridis)){install.packages("viridis")}
library(ggplot2)
library(reshape2)
library(RColorBrewer)
library(ggthemes)
library(brms)
library("ggdist")
library(viridis)
library(patchwork)
library(sjPlot)
library(multcomp)
library(lme4)
library(magrittr)
library(dplyr)
library(purrr)
library(forcats)
library(tidyr)
library(modelr)
library(ggdist)
# library(tidybayes)
library(ggplot2)
library(cowplot)
library(rstan)
library(brms)
library(ggrepel)
library(RColorBrewer)
# library(gganimate)
library(posterior)
library(distributional)
library(robustlmm)
library(performance)

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

Setup data
```{r}
raw = tibble(read.csv("data.csv"))

names(raw)<-make.names(names(raw),unique = TRUE)

data <- tibble(raw) |>
  filter(!is.na(experience), user_at_start=="AnonymousUser") |>
  mutate(id = row_number()) |>
  mutate(date_of_test2=parse_datetime(X1monthlater_created), 
         date_of_test1=parse_datetime(created),
         days =  as.integer(difftime(date_of_test2, date_of_test1)),
         days = if_else(is.na(days), 0, days),
         .before=1) |>
  # there are 2 odd data points that exist between these. Not possible so removing
  filter(days < 100 | days > 150) |>
  mutate(delay=if_else(is.na(date_of_test2), "NoFollowUp", 
                       if_else(date_of_test2 > ymd(20231010), 
                               "NineMonths", 
                               "ThreeMonths")), 
          media = factor(media),
          media = relevel(media, 'flat'),
         .before=1)

data |>
  dplyr::select(delay, experience) |>
  group_by(experience, delay, ) |>
  count()

# below, exploring that weird MIL +ve gradient bug. No evidence in the table for bug
# NB we expect NAs to be in this table
data |>
  dplyr::select(delay, experience, memory_score_T1, memory_score_T2) |>
  group_by(experience, delay, ) |>
  dplyr::summarize(mean1 = mean(memory_score_T1, na.rm=TRUE), mean2 = mean(memory_score_T2, na.rm=TRUE))

```

simple analysis
```{r}
model_data <- data |>
  #filter(days<50 | days>195) |>
  dplyr::select(id, days, media, experience, memory_score_T1, memory_score_T2, delay) |>
  pivot_longer(cols=c(memory_score_T1, memory_score_T2), 
               values_to='memory_score',
               names_to='memory_cond')  |>
  mutate(experience = factor(experience)) |>
  drop_na()


#contrasts = emmeans(fit_regular, pairwise ~ media * days , at=list(days=c(0,30, 250)) )
#contrasts
#plot(contrasts)

model_data <- model_data |>
       mutate(
        weeks = days/7
    )


model_data_discrete <- model_data |>
  mutate(
    days = case_when(
     days == 0 ~ "time0",
     days<50 & days>1 ~ "time30",
     days > 50 ~ "time250"),
    days = factor(days, levels=c('time0', 'time30', 'time250')),
  )

#fit_poly <- lmer(formula = 0 + memory_score ~  experience + media*poly(weeks,2) + (1|id), data=model_data)

fit_regular <- lmer(formula = 0 + memory_score ~  experience + media*weeks + (1|id), data=model_data)
fit_regular_robust <- rlmer(formula = 0 + memory_score ~  experience + media*weeks + (1|id), data=model_data)

#fit_regular_poly_robust <- rlmer(formula = 0 + memory_score ~  experience + media*poly(weeks,2) + (1|id), data=model_data)

fit_regular_discrete <- lmer(formula = 0 + memory_score ~  experience + media*days + (1|id), data=model_data_discrete)
contrasts = emmeans(fit_regular_discrete, pairwise ~ media * days )

plot_model(fit_poly, type = "pred", terms = c("weeks", "media"))
plot_model(fit_regular_discrete, type = "pred", terms = c("days", "media")) + geom_line()

ee <- Effect(c("media","weeks"),fit_regular) 
 model_data |>
  mutate(
    days = case_when(
     days == 0 ~ 0,
     days<50 & days>1 ~ 30,
     days > 50 ~ 250),
    days = factor(days),
  ) |>
  lmer(formula = 0 + memory_score ~  experience + media*days + (1|id)) |>
plot_model( type = "pred", terms = c("days", "media")) + geom_line(size=4) +
   ylab('Memory score') + xlab("Days") + ggtitle("") + ylim(3,12) +
   scale_fill_viridis(discrete=T) +
  theme_minimal() 

tab_model(fit_regular)
tab_model(fit_regular_discrete)


ee <- Effect(c("media","weeks"),fit_regular) 
ggplot(as.data.frame(ee),
       aes(weeks,fit,colour=media,fill=media))+
    geom_line()+
     ## colour=NA suppresses edges of the ribbon
    geom_ribbon(colour=NA,alpha=0.1,aes(ymin=lower,ymax=upper))+
     ## add rug plot based on original data
        geom_rug(data=ee$data,aes(y=NULL),sides="b") + # +  geom_smooth(method = "loess")
       # geom_smooth(data=model_data, aes(y=memory_score), method = "loess") +
       stat_summary_bin(data=model_data, aes(x=weeks, y=memory_score), fun.y=mean, geom='crossbar',) 


ee_discrete <- Effect(c("media","days"),fit_regular_discrete) 
ggplot(as.data.frame(ee_discrete),aes(days,fit_regular_discrete,colour=media,fill=media))
     ## colour=NA suppresses edges of the ribbon
   

# model_data %>%
#   group_by(media) %>%
#   add_epred_draws(fit1) %>%
#   ggplot(aes(x = days, y = memory_score, color = media)) +
#   stat_lineribbon(aes(y = .epred)) +
#   geom_point(data = model_data) +
#   scale_fill_brewer(palette = "Greys") +
#   scale_color_brewer(palette = "Set2")

# model_data %>%
#   group_by(media) %>%
#   #data_grid(days = seq_range(days, n = 30)) %>%
#   add_epred_draws(fit1) %>%
#   ggplot(aes(x = days, y = memory_score, color = ordered(media))) +
#   stat_lineribbon(aes(y = .epred)) +
#   scale_fill_brewer(palette = "Greys") +
#   scale_color_brewer(palette = "Set2")

```


fuller analysis
```{r}
all_questions = c("Q_res_1", "Q_res_2", "Q_res_3", "Q_hum_1", "Q_hum_2", "Q_hum_3", "Q_ani_1", "Q_ani_2", "Q_ani_3", "Q_lif_1", "Q_lif_2", "Q_lif_3", "Q_dee_1", "Q_dee_2", "Q_dee_3", "Q_el_1", "Q_el_2", "Q_el_3", "Q_ay_1", "Q_ay_2", "Q_ay_3", "Q_sp_1", "Q_sp_2", "Q_sp_3", "Q_dd_1", "Q_dd_2", "Q_dd_3", "Q_ss_1", "Q_ss_2", "Q_ss_3", "Q_sku_1", "Q_sku_2", "Q_sku_3", "Q_vic_1", "Q_vic_2", "Q_vic_3", "Q_met_1", "Q_met_2", "Q_met_3", "Q_mus_1", "Q_mus_2", "Q_mus_3", "Q_spa_1", "Q_spa_2", "Q_spa_3", "Q_tia_1", "Q_tia_2", "Q_tia_3", "Q_the_1", "Q_the_2", "Q_the_3", "Q_va_1", "Q_va_2", "Q_va_3", "Q_dre_1", "Q_dre_2", "Q_dre_3", "Q_shr_1", "Q_shr_2", "Q_shr_3", "X1monthlater_Q_res_1", "X1monthlater_Q_res_2", "X1monthlater_Q_res_3", "X1monthlater_Q_hum_1", "X1monthlater_Q_hum_2", "X1monthlater_Q_hum_3", "X1monthlater_Q_ani_1", "X1monthlater_Q_ani_2", "X1monthlater_Q_ani_3", "X1monthlater_Q_lif_1", "X1monthlater_Q_lif_2", "X1monthlater_Q_lif_3", "X1monthlater_Q_dee_1", "X1monthlater_Q_dee_2", "X1monthlater_Q_dee_3", "X1monthlater_Q_el_1", "X1monthlater_Q_el_2", "X1monthlater_Q_el_3", "X1monthlater_Q_ay_1", "X1monthlater_Q_ay_2", "X1monthlater_Q_ay_3", "X1monthlater_Q_sp_1", "X1monthlater_Q_sp_2", "X1monthlater_Q_sp_3", "X1monthlater_Q_dd_1", "X1monthlater_Q_dd_2", "X1monthlater_Q_dd_3", "X1monthlater_Q_ss_1", "X1monthlater_Q_ss_2", "X1monthlater_Q_ss_3", "X1monthlater_Q_tia_1", "X1monthlater_Q_tia_2", "X1monthlater_Q_tia_3", "X1monthlater_Q_the_1", "X1monthlater_Q_the_2", "X1monthlater_Q_the_3", "X1monthlater_Q_va_1", "X1monthlater_Q_va_2", "X1monthlater_Q_va_3", "X1monthlater_Q_dre_1", "X1monthlater_Q_dre_2", "X1monthlater_Q_dre_3", "X1monthlater_Q_shr_1", "X1monthlater_Q_shr_2", "X1monthlater_Q_shr_3")

prefix_for_1_month_later = 'X1monthlater_'
silly_prefix = 'Q_'


months_model_data <- data |>
  mutate_at(all_of(all_questions), as.integer) |>
  pivot_longer(cols=all_questions,
               values_to='score',
               names_to='exp_title_question') |>
  dplyr::select(id, days, media, experience, score, exp_title_question, age, ar_frequency) |>
  mutate(
     ar_frequency = case_when(
       ar_frequency == "Never" ~ 0,
       ar_frequency == "Sometimes, but less than once a month" ~ 1,
       ar_frequency == "About once a month" ~ 2,
       ar_frequency == "Several times a month" ~ 3,
       ar_frequency == "A few times a week" ~ 4,
       ar_frequency == "About daily" ~ 5
       ),
     id = factor(id),
     score = case_when(
       score == 1 ~ 1,
       score < 1 ~ 0,
       TRUE ~ NA),
     media = factor(media),
     exp_title_question = str_remove(exp_title_question,"X1monthlater_"),
     exp_title = gsub("_", "", str_extract(exp_title_question, "_.*_")),
     cohort = experience,
     months = days/30,
     # nb someone entered a stupidly high age, so we set that to NA below
     age = if_else(age < 100, age/10, NA)) |>
  drop_na()

  months_model_data |>
  mutate(
    cat_months = case_when(
      months == 0 ~ "0",
      months < 5 ~ "5",
      months < 12 ~"9"
    )
  )|>
  group_by(exp_title, cat_months) |>
  summarize(n=n()) |>
  arrange(exp_title, cat_months)

# write.table(months_model_data , file = "my_data.csv", sep=",", row.names=FALSE)


 
# exploring that weird cohort1 issue. Evidence here for it
months_model_data |>
  mutate(
    cat_months = case_when(
      months == 0 ~ "0",
      months < 5 ~ "5",
      months < 12 ~"9"
    )
  )|>
    dplyr::select(score, cat_months, cohort, media, exp_title) |>
    group_by(cohort,media, exp_title, cat_months ) |>
    dplyr::summarize(mean = mean(score, na.rm=TRUE)) |> print(n=50)


# note that we MUST NOT use exp_title_q below as it implies same Q for each experience as they have THE SAME label (1,2,3)... MUST use exp_title_question. See bottom of this link: https://rdoodles.rbind.io/2019/11/nested-random-factors-in-mixed-multilevel-or-hierarchical-models/ 
# fit1 <- brm(score ~ 1 + media * time_delay + (1 | id) + (1 | exp_title/exp_title_question), data=better_model_data, family = bernoulli(), cores=6, , control = list(adapt_delta = .90))
#load("fit_short_long.rda") # loads fit1


# below, having a look at nonlinear models.  All fairly crazy
# fit.complex <- months_model_data |> mutate(months=months+1) |> glmer(formula=score ~ 1 + age + ar_frequency + media * months + (1  | exp_title / exp_title_question) + (1 | cohort / id)  ,  family = binomial("logit"), nAGQ=0, control=glmerControl(optimizer = "nloptwrap"))
# 
# fit.complex_poly <- months_model_data |> mutate(months=months+1) |> glmer(formula=score ~ 1 + age + ar_frequency + media * poly(months, 2) + (1  | exp_title / exp_title_question) + (1 | cohort / id)  ,  family = binomial("logit"), nAGQ=0, control=glmerControl(optimizer = "nloptwrap"))
# 
# fit.complex_log <- months_model_data |> mutate(months=months+1) |> glmer(formula=score ~ 1 + age + ar_frequency + media * log(months) + (1  | exp_title / exp_title_question) + (1 | cohort / id)  ,  family = binomial("logit"), nAGQ=0, control=glmerControl(optimizer = "nloptwrap"))
# 
# fit.complex_spline <- months_model_data |> mutate(months=months+1) |> glmer(formula=score ~ 1 + age + ar_frequency + media * bs(months, knots=c(2,8)) + (1  | exp_title / exp_title_question) + (1 | cohort / id)  ,  family = binomial("logit"), nAGQ=0, control=glmerControl(optimizer = "nloptwrap"))





fit.complex <- glmer(score ~ 1 + age + ar_frequency + media * months + (1  | exp_title / exp_title_question) + (1 | cohort / id)  ,  family = binomial("logit"), data=months_model_data, nAGQ=0, control=glmerControl(optimizer = "nloptwrap"))

fit.marusa_basic <- glmer(score ~ 1 + media * months + (1  + months | id) ,  family = binomial("logit"), data=months_model_data, nAGQ=0, control=glmerControl(optimizer = "nloptwrap"))

fit.marusa <- glmer(score ~ 1 + media * months * cohort + (1  + months | id),  family = binomial("logit"), data=months_model_data, nAGQ=0, control=glmerControl(optimizer = "nloptwrap"))
fit.marusa_no_random <- glm(score ~ 1 + media * months * exp_title,  family = binomial("logit"), data=months_model_data)
plot_model(fit.marusa_no_random, type = "pred", terms = c("months [all]", "media", "exp_title"), ci.lvl=0.95)  + theme_minimal() + geom_rug(sides='b', alpha = 1/2, position = "jitter")

months_model_data |>
  filter(cohort == 1) |>
    ggplot(aes(x=months, y=score)) + geom_smooth(aes(color=media), method="glm",
    method.args=list(family="binomial")) + facet_wrap(~ exp_title_question)




plot_model(fit.complex, type = "pred", terms = c("months [all]", "media"), ci.lvl=0.95)  + theme_minimal() + geom_rug(sides='b', alpha = 1/2, position = "jitter")

plot_model(fit.complex, type = "pred", terms = c("exp_title", "exp_title_question"), pred.type='re', ci.lvl=NA, colors = 'darkgray', show.legend = T,)  + theme_minimal()
plot_model(fit.complex, type = "re", facet.grid=FALSE) 




fit.full2 <- glmer(score ~ 1 + age + ar_frequency + presence + media * months + (1 + months | id) + (1 + months | exp_title / exp_title_question) ,  family = binomial("logit"), data=months_model_data, nAGQ=0, control=glmerControl(optimizer = "nloptwrap"))

fit.no_interaction <- glmer(score ~ 1 + age + ar_frequency + media + months + (1 + months | id) + (1 + months | exp_title / exp_title_question) ,  family = binomial("logit"), data=months_model_data, nAGQ=0, control=glmerControl(optimizer = "nloptwrap"))

anova(fit.no_interaction, fit.full)
fit.no_interaction: score ~ 1 + age + ar_frequency + media + months + (1 + months | id) + (1 + months | exp_title/exp_title_question)
#                    npar   AIC   BIC logLik deviance  Chisq Df Pr(>Chisq)   
# fit.no_interaction   19 65810 65979 -32886    65772                        
# fit.full             20 65805 65983 -32883    65765 6.7897  1   0.009169 **
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

graph_rand_effects_months_x_exptitle <- plot_model(fit.full, type = "pred", terms = c("months[all]", "exp_title"), pred.type='re', ci.lvl=NA) + geom_rug(sides='b', alpha = 1/2, position = "jitter")
graph_rand_effects_months_x_exptitle



graph_rand_effects_q_x_exptitle <- plot_model(fit.full, type = "pred", terms = c("exp_title", "exp_title_question"), pred.type='re', ci.lvl=NA, colors = 'darkgray', show.legend = T, dot.size=3, dodge = 0, alpha=.5)  + theme_minimal()
graph_rand_effects_q_x_exptitle

# nb cant generate plot of months months x id as we have 1000s of id


graph_interaction <- plot_model(fit.full, type = "pred", terms = c("months [all]", "media"))  + theme_minimal() + geom_rug(sides='b', alpha = 1/2, position = "jitter")
graph_interaction

emtrends(fit.full, pairwise~media, var="months")
emmip(fit.full, media ~ months, cov.reduce = range, CIs=T, type='response') + 
  theme_minimal()

```
